server:
  standalone:
    enabled: true
    config: |
      listener "tcp" {
        address     = "[::]:8200"
        tls_disable = 1
      }
      storage "raft" {
        path = "/vault/data"
      }
      disable_mlock = true

  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: local-path

injector:
  enabled: true   
